core:
        database: Aks\App\Core\Database
        session: Aks\App\Core\Session

          
repository:
        utilisateurRepository: Aks\Src\Repository\UtilisateurRepository
        compteRepository: Aks\Src\Repository\CompteRepository
        transactionRepository: Aks\Src\Repository\TransactionRepository

            
service:
        securityService: Aks\Src\Service\SecurityService
        compteService: Aks\Src\Service\CompteService     
        transactionService: Aks\Src\Service\TransactionService     
